[package]
name = "cef2hashmap"
description = "A Simple CEF Parser to a HashMap"
version = "0.1.5"
authors = ["Marirs <marirs@gmail.com>", "jyoung15@users.noreply.github.com"]
keywords = ["cef", "json", "event"]
categories = ["parsing"]
exclude = ["examples"]
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/marirs/cef2hashmap-rs"
repository = "https://github.com/marirs/cef2hashmap-rs"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.12", default-features = false }

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
debug-assertions = false
debug = false
opt-level = 3
lto = true

[lints.rust]
deprecated-in-future = "warn"
redundant-imports = "warn"
redundant-lifetimes = "warn"
trivial-casts = "warn"
trivial-numeric-casts = "warn"
unit-bindings = "warn"
unused-crate-dependencies = "warn"
unused-extern-crates = "warn"
unused-import-braces = "warn"
unused-lifetimes = "warn"
unused-macro-rules = "warn"
unused-mut = "warn"
unused-qualifications = "warn"
unsafe-code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
ptr_arg = "warn"
cargo = { level = "warn", priority = -1 }
unused_trait_names = "warn"
unwrap_used = "warn"
panic = "warn"
